### ISSUE TITLE
Raises a Gem::ConflictError from the start

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/intro-to-capybara#12]
This lesson raises a Gem::Conflict error from the start so am unable to actually proceed with the lesson....beginning of error message is below

`usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_co
nflicts': Unable to activate sinatra-1.4.7, because rack-2.0.1 conflicts with rack (~> 1.5) (Gem::Confli
ctError)   `

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
This lab doesn't specify any dependencies (looking into why that's the case) -- I've added a Gemfile which _might_ fix the issue. Could you try again and let me know?

**Comment by sandyvern** [comment]
I got it to run by uninstalling rack 2.0.1 and then it would let me run learn and pass tests.

**Comment by pletcher** [comment]
Great, thanks!
