### ISSUE TITLE
Capybara Tests won't run because of gem conflict.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/intro-to-capybara#15]
These are from an open issue on learn-co-students. Ran into this issue with a student today and their steps resolved it.

ran tests after doing the code for the first half of the readme and got the following error:
Unable to activate sinatra-1.4.7, 
because rack-2.0.1 conflicts with rack (~> 1.5) (Gem::ConflictError)

I was able to resolve this issue by running 'gem uninstall sinatra' and 'gem uninstall rack' (uninstalled all versions and said yes to every prompt). then, ran bundle install again.

Uninstalling the gems and bundle install fixed it so I assume the gemfile just needs to be updated.

**Comment by bhollan** [comment]
Issue in question: [#224](https://github.com/learn-co-students/intro-to-capybara-v-000/issues/224)

@aturkewi

**Comment by EoghanL** [comment]
A further heads up that `Gemfile.lock` needs to be deleted before `bundle install` is run.
