### ISSUE TITLE
bundler: failed to load command: rspec (/usr/local/rvm/gems/ruby-2.3.1/bin/rspec)

### ISSUE THREAD

**Issue by hillevieklow** [learn-co-curriculum/intro-to-capybara#27]
**Running _learn_ or _rspec_ in terminal raises the following error:** 

`bundler: failed to load command: rspec (/usr/local/rvm/gems/ruby-2.3.1/bin/rspec)
RuntimeError: missing run or map statement
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:146:in `to_app'
  config.ru:3:in `<main>'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
  /home/hillevieklow/intro-to-capybara-v-000/spec/spec_helper.rb:16:in `app'
  /home/hillevieklow/intro-to-capybara-v-000/spec/spec_helper.rb:20:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_
options_into'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_i
nto'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
  /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `<top (required)>'`

**Comment by hillevieklow** [comment]
<img width="846" alt="screen shot 2018-07-11 at 10 03 25 am" src="https://user-images.githubusercontent.com/23427813/42577003-b25c104e-84f1-11e8-92e0-1c41e2211036.png">

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
