### ISSUE TITLE
Contradictory Infographic

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/intro-to-capybara#28]
"**INTEGRATION TESTS:** ...Commonly referred to as '**End-to-End' tests**, integration tests **should flex your entire application stack** (i.e., all of the MVC components) and **rarely isolate components** or behaviors..."
![screen shot 2018-08-29 at 11 23 59 am](https://user-images.githubusercontent.com/6418313/44801340-6bf13900-ab7e-11e8-9fd9-0f13cf8c1c32.png)

**Comment by sgharms** [comment]
Good point. I added some clarification in 4cd42a9b038e46114b26f41e4b204d33b881510a.

As a UT grad, much love to South Austin from South of Houston (that is the street, in Manhattan :) )

Ship Torchy's!
