### ISSUE TITLE
There is an instruction to fork and clone this readme

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/intro-to-capybara#3]
"Now that our test suite is setup to use Capybara, let's start writing some tests for our application. Everything is already built and included with this lesson if you fork and clone it or you can rebuild it on your own by copying the code into the files."

But lesson is a readme and can't currently be opened with the learn button. Unclear if users will remember the git workflow at this point to get it done on their own

**Comment by AnnJohn** [comment]
closing for now, since students will know to fork and clone by the time they're in the Full Stack track where this is at now.
