### ISSUE TITLE
config.ru instructions should be shown sooner

### ISSUE THREAD

**Issue by artismarti** [learn-co-curriculum/intro-to-capybara#30]
Without the 
```
require 'sinatra'
require_relative './app'

run Application
```
code in config.ru the learn command does not run. A rack error is shown. 
```
/Users/myname/.rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/builder.rb:146:in `to_app': missing run or map statement (RuntimeError)
```

This instruction should be moved up in the README

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @artismarti.

We have updated the order of instructions in this readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by artismarti** [comment]
Thank you 🙏
