### ISSUE TITLE
The README and application_integration_spec.rb aren't in sync

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/intro-to-capybara#31]
Since this is a code-along lab, the instructions in the readme file refer to steps that are already taken in the application_integration_spec.rb file when it is forked.   This caused some confusion and also makes most of the first portion of the readme not make much sense because it tells you what errors you should see and you are seeing different errors.   Someone should go back and remove most of the code from application_integration_spec.rb so it only includes the first section so the user sees the errors as they progress through the readme and correct them.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
