### ISSUE TITLE
No Gemfile, and rspec not done

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/intro-to-capybara#6]
It says in the lesson "All of the code we will review below is already present in this repo. You can fork and clone this repo to take a closer look, or you can rebuild this simple app on your own as we review it together, below.". Couldn't bundle install due to no gemfile present. Also the rspec for "application_integration_spec.rb" wasn't completed(which i would of added the code myself, but i'm not sure which gems you wanted installed which was the main issue).

**Comment by mendelB** [comment]
@Enoch2k2 Thanks so much for the submission!
This lab doesn't need a Gemfile/bundle install.
The point of the lab is to learn how Capybara integration testing works by following the Readme and filling in the `spec/application_integration_spec.rb` file.
I'm going to go ahead and close this issue, Thanks again!
