### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by Richard-Frost** [learn-co-curriculum/intro-to-capybara#8]
It seems like this is forked with the corrected code already included.  Tests are supposed to fail but pass.

**Comment by AnnJohn** [comment]
hi @Richard-Frost all the code is supposed to already be there as per what's stated under the section "Testing our Application"
- "All of the code we will review below is already present in this repo. You can fork and clone this repo to take a closer look, or you can rebuild this simple app on your own as we review it together, below." 

Thanks!
